name: New Push Master

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.10.3'
    - run: flutter pub get
    - run: flutter build apk --split-per-abi
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/*"
        tag: v1.0.${{github.run_number }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - uses: papeloto/action-zip@v1
      with:
        files: "build/app/outputs/flutter-apk/app-x86_64-release.apk"
        dest: package${{github.run_number }}.zip
    - name : Upload Arrifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: package${{github.run_number }}.zip
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: "build/app/outputs/flutter-apk/app-x86_64-release.apk"


#   sendemails:
#     runs-on: ubuntu-18.04
#     steps:
#      - name: Send mailz
#        uses: dawidd6/action-send-mail@v3
#        with:
#         # Required mail server address:
#         server_address: smtp.gmail.com
#         # Required mail server port:
#         server_port: 465
#         # Optional (recommended): mail server username:
#         username: ${{secrets.MAIL_USERNAME}}
#         # Optional (recommended) mail server password:
#         password: ${{secrets.MAIL_PASSWORD}}
#         # Required mail subject:
#         subject: New App Release For Testing (AtechCoins)
#         # Required recipients' addresses:
#         # to: gisgreat335@gmail.com,ayoayomide124@gmail.com
#         to: gisgreat335@gmail.com
#         # Required sender full name (address can be skipped):
#         from: atechcoins@gmail.com # <user@example.com>
#         # Optional whether this connection use TLS (default is true if server_port is 465)
#         secure: true
#         # Optional plain body:
#         body: New AtechCoins App release completed successfully. Check Our Dropbox Folder to view files and run tests!
#         # Optional HTML body read from file:
# #         html_body: file://README.html
#         # Optional carbon copy recipients:
# #         cc: kyloren@example.com,leia@example.com
#         # Optional blind carbon copy recipients:
# #         bcc: r2d2@example.com,hansolo@example.com
#         # Optional recipient of the email response:
# #         reply_to: luke@example.com
#         # Optional unsigned/invalid certificates allowance:
#         ignore_cert: true
#         # Optional converting Markdown to HTML (set content_type to text/html too):
#         convert_markdown: true
#         # Optional attachments:
#         attachments: "build/app/outputs/flutter-apk/app-x86_64-release.apk"
#         # Optional priority: 'high', 'normal' (default) or 'low'
#         priority: normal


